name: CyberPlugin
version: 1.0-SNAPSHOT
main: com.cyberdev.cyberplugin.CyberPlugin
api-version: 1.13
authors: [sentosa]
description: private cyber plugin
commands:
  inf:
    description: testing cmd for inf class gadget